# -*- coding: utf-8 -*-
"""CruiseLInepredictions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gU-GAJzh3i3eugHvxMWSCtxW2_WrUrk9
"""

#A batch of data about cruises is given because the number of customers is needed

from google.colab import files

upload = files.upload()

pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("owo").getOrCreate()

dpf = spark.read.csv("cruise_ship_info.csv",inferSchema=True,header=True).drop("Cruise_line")

dpf.show(10)

from pyspark.ml.regression import LinearRegression

from pyspark.ml.linalg import Vectors
from pyspark.ml.feature import VectorAssembler

dpf.columns

assembler = VectorAssembler(inputCols=['Age',
 'Tonnage',
 'passengers',
 'length',
 'cabins',
 'passenger_density'],outputCol="feature")

output = assembler.transform(dpf)

output.printSchema()

output.show(5)

train_data, test_data = output.randomSplit([0.7,0.3])

lr = LinearRegression(featuresCol="feature",labelCol="crew")

lr_model = lr.fit(train_data)

test_results = lr_model.evaluate(test_data)

test_results.residuals.show()

test_results.rootMeanSquaredError

from pyspark.sql.functions import corr

test_results.meanAbsoluteError

dpf.show()

dpf.select(corr("crew","cabins")).show()

dpf.select(corr("crew","Tonnage")).show()

dpf.select(corr("crew","passengers")).show()

#A high correlation between all the variables is given by our model, such as expected